name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Check terraform format
        run: terraform fmt -check -diff -recursive .
